### ISSUE TITLE
simplify interpolation

### ISSUE THREAD

**Issue by balhoff** [dosumis/dead_simple_owl_design_patterns#19]
It seems like template files could be simplified if the interpolation used variable names instead of requiring the list of positions. Instead of this:

``` yaml
vars: 
  quality: "'Thing'"
  entity: "'Thing'"
  location: "'Thing'"

name:
  text: "%s %s in %s"
  vars:
    - quality
    - entity
    - location

equivalentTo: 
  text: "%s and 'inheres in' some (%s and 'part of' some %s)"
  vars:
    - quality
    - entity
    - location
```

What about this:

``` yaml
vars: 
  quality: "'Thing'"
  entity: "'Thing'"
  location: "'Thing'"

name:
  text: "$quality $entity in $location"

equivalentTo: 
  text: "$quality and 'inheres in' some ($entity and 'part of' some $location)"
```

No need for the `vars` property in every section.
