### ISSUE TITLE
Define how identifiers are expanded to IRIs

### ISSUE THREAD

**Issue by balhoff** [dosumis/dead_simple_owl_design_patterns#21]
Patterns I have seen use a mix of ID styles including both e.g. `GO_0016020` and `GO:0016020`. Templates could contain a `prefixes` key containing mappings. This would be more straightforward than a full-blown JSON-LD context. Non-CURIE IDs such as `GO_0016020` could be supported by also having a `base` key. Example:

``` yaml
pattern_name: oba/patterns/entity_attribute
classes: []

prefixes:
  RO: http://purl.obolibrary.org/obo/RO_

base: http://purl.obolibrary.org/obo/

relations:
  part of: BFO_0000050
  inheres in: RO:0000052
  inheres in part of: RO_0002314
```

Since there are no literals I don't know that we need to wrap in `<>` to distinguish unprefixed IRIs from CURIEs.
