### ISSUE TITLE
Idea: non-logical restrictions for variable fillers

### ISSUE THREAD

**Issue by balhoff** [dosumis/dead_simple_owl_design_patterns#25]
This just came up in a Monarch all hands discussion; not sure how useful or required it may be. But someone may want to specify a 'slim' or some other annotation as a way to restrict available terms.

**Comment by dosumis** [comment]
Already possible with data_vars & data_list_vars.

**Comment by balhoff** [comment]
I think we might be talking about different things, but please correct me if not. I mean that if some one has these variables in their pattern:

```yaml
vars: 
  membrane: "'membrane'"
  cargo: "'chemical entity' or 'macromolecular complex' or 'transcript'"
  start: "'cellular_component'"
  end: "'cellular_component'"
```

Instead of saying that `start` needs to be a logical subclass of `cellular_component`, they may want to say that all fillers for `start` need to be in some slim (i.e. all allowable classes have a particular `in_subset` annotation value).
