### ISSUE TITLE
Make vars optional in 'printf' fields?

### ISSUE THREAD

**Issue by dosumis** [dosumis/dead_simple_owl_design_patterns#39]
Patterns sometimes need to spec a constant filler for an axiom.  e.g. patterns in GO require a namespace to be specified for all implementations of the patterns.   We can also imagine cases where we want to spec a constant SubClassOf axiom (=> consistent GCI) - although this may be a slightly dangerous approach.

In the current spec we could support this by forcing spec of an empty vars list in a pattern.  But a more compact solution is simply to allow the vars field to be optional.  

=> 

```yaml
namespace:
   text: biological_process
```

While dropping the text field altogether would look cleaner in this case, this is harder to build on top of the core spec, where we still need an annotationProperty field:

```yaml
annotations:
   -
       annotationProperty: obo_namespace
       text: biological_process
```
